### PR TITLE
Fix issues associated with changing opacity dynamically

### PR DESCRIPTION
**Pull request by keithdmoore**

### CODE REVIEW

**Comment by mlynch** [comment]
Hey @keithdmoore I'm noticing the transparency starts > 0 which is not like Tinder. Mind if I make it start at 0?

**Comment by mlynch** [comment]
Okay, I see why you did that (really slow at first). Really I think it just needs a non-linear ramp. I'll do that now.

**Comment by keithdmoore** [comment]
Ok.  Sounds good.

**Comment by mlynch** [comment]
Okay, I added a cubic-bezier function that starts from 0 and fades up quickly, but then slowly ramps out. Hopefully doesn't add a perf hit with the fn calls...

**Pull request merged**
